### ISSUE TITLE
Bitcoin 

### ISSUE THREAD

**Issue by ChakTochi** [ummjackson/awdy#47]
# of entities in control of >50% of voting/mining power = 4 (not 3)

https://www.blockchain.com/fr/pools

**Comment by jotto** [comment]
btc.com and antpool are both owned by bitmain, so that means (from the "4 days" data): 

* bitmain: 16.8+14.6
* unknown: 13.6
* btc.top: 12.2
* **top 3 = 57.2%**


here's documentation of bitmain acquiring btc.com (July 2016) https://blog.btc.com/blocktrail-is-now-a-part-of-the-bitmain-family-ec937f5ab3b7

Here is CCN emphasizing bitmain's hashing power (june 2018): https://www.ccn.com/bitmains-mining-pools-now-control-nearly-51-percent-of-the-bitcoin-hashrate/
